# ==============================================================================
# Script 2: Population under status quo and disease-elimination counterfactuals
# ==============================================================================
#
# Purpose:
#   1. Prepare age- and sex-specific population data for 2019-2050.
#   2. Construct disease-specific counterfactual population trajectories by
#      removing disease-related mortality.
#   3. Propagate the GBD 2021 point estimate and lower/upper epidemiological
#      bounds through the counterfactual population calculation.
#
# Population data:
#   Source/version: United Nations, Department of Economic and Social Affairs
# https://population.un.org/wpp/Download/Standard/Population/
#   Files:
#     - population_male.xlsx
#     - population_female.xlsx
#   Sheets used:
#     - "Estimates"
#     - "Medium variant"
#   Unit in source files: thousands of persons
#   Download date: [2026-02-06]
#
# Mortality input:
#   Dataset: Global Burden of Disease Study 2021 (GBD 2021)
#   Download date: 2026-02-06
#   Input file: death_1950_n.csv
#   This file is generated by Script 1 (1_Mortality_morbidity_UI_clean.R).
#
# Reproducibility:
#   Random seed: Not applicable. This script contains no stochastic procedures.
#   R version: 4.2.1
#   Platform: x86_64-pc-linux-gnu (64-bit)
#   Operating system: Ubuntu 22.04.2 LTS
#   Package versions:
#     - readxl:   1.4.3
#     - dplyr:   1.1.4
#     - tidyr:   1.3.0
#     - progress: 1.2.3
#
# ==============================================================================


# ------------------------------------------------------------------------------
# 1. Packages
# ------------------------------------------------------------------------------

library(readxl)
library(dplyr)
library(tidyr)
library(progress)


# ------------------------------------------------------------------------------
# 2. Status quo population data
# ------------------------------------------------------------------------------

# Male population
num1 <- read_xlsx(
  "/dssg/home/acct-wenze.zhong/jingxuanw/economic2/data/data/population/population_male.xlsx",
  sheet = "Estimates",
  col_names = FALSE
)

colname <- read_xlsx(
  "/dssg/home/acct-wenze.zhong/jingxuanw/economic2/data/data/population/population_male.xlsx",
  sheet = "Estimates",
  col_names = FALSE,
  n_max = 1
)

colnames(num1) <- colname
num1 <- num1[-1, ]

num2 <- read_xlsx(
  "/dssg/home/acct-wenze.zhong/jingxuanw/economic2/data/data/population/population_male.xlsx",
  sheet = "Medium variant",
  col_names = FALSE
)

colnames(num2) <- colname
num2 <- num2[-1, ]

num_male <- num1 %>%
  rbind(num2) %>%
  mutate(sex = "male")


# Female population
num1 <- read_xlsx(
  "/dssg/home/acct-wenze.zhong/jingxuanw/economic2/data/data/population/population_female.xlsx",
  sheet = "Estimates",
  col_names = FALSE
)

colnames(num1) <- colname
num1 <- num1[-1, ]

num2 <- read_xlsx(
  "/dssg/home/acct-wenze.zhong/jingxuanw/economic2/data/data/population/population_female.xlsx",
  sheet = "Medium variant",
  col_names = FALSE
)

colnames(num2) <- colname
num2 <- num2[-1, ]

num_female <- num1 %>%
  rbind(num2) %>%
  mutate(sex = "female")


# ------------------------------------------------------------------------------
# 3. Mortality inputs for the counterfactual scenario
# ------------------------------------------------------------------------------

death <- read.csv(
  "/dssg/home/acct-wenze.zhong/jingxuanw/economic2/outcome/rural outcome/air&met/death_1950_n.csv"
)

death_n <- death[, 2:9]


# ------------------------------------------------------------------------------
# 4. Reshape population data
# ------------------------------------------------------------------------------

# Keep detailed age groups at this stage; ages 65+ are aggregated after the
# counterfactual population calculation.
num <- num_male %>%
  rbind(num_female) %>%
  subset(Year >= 2019 & Year <= 2050) %>%
  select(c(6, 33, 11:32)) %>%
  arrange(`ISO3 Alpha-code`, sex, Year) %>%
  mutate(across(4:24, as.numeric)) %>%
  # GBD uses a single 95+ age group.
  mutate(`95+` = `95-99` + `100+`) %>%
  select(c(1:22, 25))

num_n <- num %>%
  pivot_longer(
    cols = c(
      "0-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34",
      "35-39", "40-44", "45-49", "50-54", "55-59", "60-64",
      "65-69", "70-74", "75-79", "80-84", "85-89", "90-94", "95+"
    ),
    names_to = "age",
    values_to = "number"
  )

num_n <- num_n[!is.na(num_n$`ISO3 Alpha-code`), ]

nt_n <- num_n %>%
  rename(
    WBcode = `ISO3 Alpha-code`,
    year = Year
  ) %>%
  # Source population values are reported in thousands.
  mutate(number = number * 1000) %>%
  arrange(WBcode, sex, year) %>%
  group_by(WBcode, sex, year)

write.csv(
  nt_n,
  "/dssg/home/acct-wenze.zhong/jingxuanw/economic2/outcome/rural outcome/air&met/number_1950_origin.csv"
)


# ------------------------------------------------------------------------------
# 5. Prepare inputs for disease-elimination counterfactual populations
# ------------------------------------------------------------------------------

# The counterfactual calculation starts in 2019. Population in 2019 is identical
# in the status quo and counterfactual scenarios.
Nt <- death_n %>%
  merge(
    nt_n,
    by = c("WBcode", "year", "sex", "age"),
    all.x = TRUE
  ) %>%
  select(c(5, 1, 3, 2, 4, 6:9)) %>%
  arrange(cause_name, WBcode, sex, year)

# Some disease-age combinations have no reported mortality at younger ages.
# These combinations were set to zero in Script 1 when the complete input grid
# was created.

Nt_19 <- Nt %>%
  subset(year == "2019") %>%
  select(c(1:5, 9)) %>%
  rename(N = number)

Nt_2050 <- Nt %>%
  filter(year != "2019")

disease_name <- unique(Nt$cause_name)
country_code <- unique(Nt$WBcode)
sex_name <- unique(Nt$sex)

age_name <- c(
  "0-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34",
  "35-39", "40-44", "45-49", "50-54", "55-59", "60-64",
  "65-69", "70-74", "75-79", "80-84", "85-89", "90-94", "95+"
)

year_name <- 2019:2050


# ------------------------------------------------------------------------------
# 6. Helper function for matrix extraction
# ------------------------------------------------------------------------------

data_matrix <- function(data, a, t, measure) {
  data_sel <- data %>%
    subset(age == a & year == t) %>%
    select(c("cause_name", "WBcode", measure))

  return(data_sel)
}


# ------------------------------------------------------------------------------
# 7. Calculate disease-specific counterfactual population
# ------------------------------------------------------------------------------

calculate_N <- function(data, s) {

  data_m <- data %>%
    subset(sex == s) %>%
    mutate(
      D_val = 1 - val,
      D_lower = 1 - lower,
      D_upper = 1 - upper
    )

  Nt_ca <- as.data.frame(matrix(nrow = 0, ncol = 7))

  total_iterations <- n_distinct(data$age) * n_distinct(data$year)

  pb <- progress_bar$new(
    format = "Calculating [:bar] :percent | :current/:total | eta: :eta",
    total = total_iterations,
    width = 60
  )

  for (a in 1:n_distinct(data$age)) {

    Nt_ct <- as.data.frame(matrix(nrow = 0, ncol = 6))

    for (t in 1:n_distinct(data$year)) {

      pb$tick()

      # The matrix dimensions depend on the number of countries and diseases
      # in the current analysis (204 countries and 55 columns here).
      result_val <- as.data.frame(matrix(1, nrow = 204, ncol = 55))
      result_lower <- as.data.frame(matrix(1, nrow = 204, ncol = 55))
      result_upper <- as.data.frame(matrix(1, nrow = 204, ncol = 55))

      data_N <- data_matrix(
        data_m,
        age_name[a],
        year_name[t],
        "number"
      )

      N_matrix <- spread(
        data_N,
        key = cause_name,
        value = number
      )

      N_matrix <- select(N_matrix, c(2:56))

      if (min(a, t) == 1 | t < 6) {

        result_val <- N_matrix
        result_lower <- N_matrix
        result_upper <- N_matrix

      } else {

        for (i in 0:(min(a, floor((t + 4) / 5)) - 2)) {

          # Point estimate: calculate cumulative survival probabilities over the
          # relevant preceding 5-year periods.
          data_D1 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 5 - 5 * i], "D_val"
          )
          data_D2 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 4 - 5 * i], "D_val"
          )
          data_D3 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 3 - 5 * i], "D_val"
          )
          data_D4 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 2 - 5 * i], "D_val"
          )
          data_D5 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 1 - 5 * i], "D_val"
          )

          D1_matrix <- spread(data_D1, key = cause_name, value = D_val)
          D1_matrix <- select(D1_matrix, c(2:56))
          D2_matrix <- spread(data_D2, key = cause_name, value = D_val)
          D2_matrix <- select(D2_matrix, c(2:56))
          D3_matrix <- spread(data_D3, key = cause_name, value = D_val)
          D3_matrix <- select(D3_matrix, c(2:56))
          D4_matrix <- spread(data_D4, key = cause_name, value = D_val)
          D4_matrix <- select(D4_matrix, c(2:56))
          D5_matrix <- spread(data_D5, key = cause_name, value = D_val)
          D5_matrix <- select(D5_matrix, c(2:56))

          result_val <- (
            result_val *
            D1_matrix *
            D2_matrix *
            D3_matrix *
            D4_matrix *
            D5_matrix
          )

          # Lower GBD epidemiological bound.
          data_D1 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 5 - 5 * i], "D_lower"
          )
          data_D2 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 4 - 5 * i], "D_lower"
          )
          data_D3 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 3 - 5 * i], "D_lower"
          )
          data_D4 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 2 - 5 * i], "D_lower"
          )
          data_D5 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 1 - 5 * i], "D_lower"
          )

          D1_matrix <- spread(data_D1, key = cause_name, value = D_lower)
          D1_matrix <- select(D1_matrix, c(2:56))
          D2_matrix <- spread(data_D2, key = cause_name, value = D_lower)
          D2_matrix <- select(D2_matrix, c(2:56))
          D3_matrix <- spread(data_D3, key = cause_name, value = D_lower)
          D3_matrix <- select(D3_matrix, c(2:56))
          D4_matrix <- spread(data_D4, key = cause_name, value = D_lower)
          D4_matrix <- select(D4_matrix, c(2:56))
          D5_matrix <- spread(data_D5, key = cause_name, value = D_lower)
          D5_matrix <- select(D5_matrix, c(2:56))

          result_lower <- (
            result_lower *
            D1_matrix *
            D2_matrix *
            D3_matrix *
            D4_matrix *
            D5_matrix
          )

          # Upper GBD epidemiological bound.
          data_D1 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 5 - 5 * i], "D_upper"
          )
          data_D2 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 4 - 5 * i], "D_upper"
          )
          data_D3 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 3 - 5 * i], "D_upper"
          )
          data_D4 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 2 - 5 * i], "D_upper"
          )
          data_D5 <- data_matrix(
            data_m, age_name[a - 1 - i], year_name[t - 1 - 5 * i], "D_upper"
          )

          D1_matrix <- spread(data_D1, key = cause_name, value = D_upper)
          D1_matrix <- select(D1_matrix, c(2:56))
          D2_matrix <- spread(data_D2, key = cause_name, value = D_upper)
          D2_matrix <- select(D2_matrix, c(2:56))
          D3_matrix <- spread(data_D3, key = cause_name, value = D_upper)
          D3_matrix <- select(D3_matrix, c(2:56))
          D4_matrix <- spread(data_D4, key = cause_name, value = D_upper)
          D4_matrix <- select(D4_matrix, c(2:56))
          D5_matrix <- spread(data_D5, key = cause_name, value = D_upper)
          D5_matrix <- select(D5_matrix, c(2:56))

          result_upper <- (
            result_upper *
            D1_matrix *
            D2_matrix *
            D3_matrix *
            D4_matrix *
            D5_matrix
          )
        }

        # Counterfactual population equals the status quo population divided by
        # the cumulative survival probability associated with disease-specific
        # mortality.
        result_val <- N_matrix / result_val
        result_lower <- N_matrix / result_lower
        result_upper <- N_matrix / result_upper
      }

      result_val$WBcode <- country_code
      result_lower$WBcode <- country_code
      result_upper$WBcode <- country_code

      # Convert matrices back to long format.
      result_val_data <- gather(
        data = as.data.frame(result_val),
        key = "cause_name",
        value = "N_val",
        -WBcode
      )

      result_lower_data <- gather(
        data = as.data.frame(result_lower),
        key = "cause_name",
        value = "N_lower",
        -WBcode
      )

      result_upper_data <- gather(
        data = as.data.frame(result_upper),
        key = "cause_name",
        value = "N_upper",
        -WBcode
      )

      result_data <- result_val_data %>%
        merge(
          result_lower_data,
          by = c("cause_name", "WBcode")
        )

      result_data <- result_data %>%
        merge(
          result_upper_data,
          by = c("cause_name", "WBcode")
        )

      result_data$year <- year_name[t]
      Nt_ct <- rbind(Nt_ct, result_data)
    }

    Nt_ct$age <- age_name[a]
    Nt_ca <- rbind(Nt_ca, Nt_ct)
  }

  Nt_ca$sex <- s

  return(Nt_ca)
}


# Calculate counterfactual population separately by sex.
Nt_cm <- calculate_N(Nt, "male")
Nt_cf <- calculate_N(Nt, "female")

Nt_c <- Nt_cm %>%
  rbind(Nt_cf) %>%
  select(c(2, 1, 8, 6, 7, 3:5)) %>%
  arrange(cause_name, WBcode, sex, year, age)


# ------------------------------------------------------------------------------
# 8. Aggregate ages 65+ and retain working-age groups
# ------------------------------------------------------------------------------

combine_N <- function(data) {

  # Aggregate all age groups 65+ into a single 65+ category.
  filtered_data <- data %>%
    filter(
      age %in% c(
        "65-69", "70-74", "75-79", "80-84",
        "85-89", "90-94", "95+"
      )
    ) %>%
    arrange(cause_name, WBcode, sex, year, age) %>%
    group_by(cause_name, WBcode, sex, year) %>%
    mutate(
      N_val = sum(N_val),
      N_lower = sum(N_lower),
      N_upper = sum(N_upper),
      age = "65+"
    ) %>%
    distinct(
      cause_name,
      WBcode,
      year,
      sex,
      .keep_all = TRUE
    )

  # Remove the original 65+ age groups and populations younger than 15 years.
  data_new <- data %>%
    filter(
      !(
        age %in% c(
          "0-4", "5-9", "10-14",
          "65-69", "70-74", "75-79", "80-84",
          "85-89", "90-94", "95+"
        )
      )
    )

  data_final <- data_new %>%
    bind_rows(filtered_data) %>%
    arrange(cause_name, WBcode, sex, year, age)

  return(data_final)
}

Nt_cn <- combine_N(Nt_c)


# ------------------------------------------------------------------------------
# 9. Export
# ------------------------------------------------------------------------------

write.csv(
  Nt_cn,
  "/dssg/home/acct-wenze.zhong/jingxuanw/economic2/outcome/rural outcome/air&met/number_cf_1950_ui.csv"
)
